#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""

Executable for the model wrapper of the twopoppy code. Use option `-h` to
see the help


Created on Tue Jun  6 16:42:01 2017

@author: birnstiel
"""
def main():
    import argparse
    from twopoppy import const as c
    from twopoppy import args
    from twopoppy import wrapper
    #
    # =================
    # ARGUMENT HANDLING
    # =================
    #
    # read in arguments
    #
    RTHF = argparse.RawTextHelpFormatter
    PARSER = argparse.ArgumentParser(description=__doc__,formatter_class=RTHF)
    PARSER.add_argument('-nr',    help='number of radial grid points',         type=int,   default=200)
    PARSER.add_argument('-nt',    help='number of snapshots',                  type=int  , default=100)
    PARSER.add_argument('-na',    help='number of particle sizes (use many!)', type=int  , default=150)
    PARSER.add_argument('-tmax',  help='simulation end time [yr]',             type=float, default=1e6)
    PARSER.add_argument('-alpha', help='turbulence parameter',                 type=float, default=1e-3)
    PARSER.add_argument('-d2g',   help='dust-to-gas ratio',                    type=float, default=1e-2)
    PARSER.add_argument('-mstar', help='stellar mass [solar masses]',          type=float, default=0.7)
    PARSER.add_argument('-tstar', help='stellar temperature [K]',              type=float, default=4010.)
    PARSER.add_argument('-rstar', help='stellar radius [solar radii]',         type=float, default=1.806)
    PARSER.add_argument('-rc',    help='disk characteristic radius [AU]',      type=float, default=200)
    PARSER.add_argument('-rt',    help='outer disk truncation radius [AU]',    type=float, default=1e6)
    PARSER.add_argument('-mdisk', help='disk mass in central star masses',     type=float, default=0.1)
    PARSER.add_argument('-rhos',  help='bulk density of the dusg [ g cm^-3]',  type=float, default=1.156)
    PARSER.add_argument('-vfrag', help='fragmentation velocity [ cm s^-1]',    type=float, default=1000)
    PARSER.add_argument('-a0',    help='initial grain size [cm]',              type=float, default=1e-5)
    PARSER.add_argument('-gamma', help='viscosity: alpha*(r/r[0])**gamma',     type=float, default=1)
    PARSER.add_argument('-edrift',help='drift fudge factor',                   type=float, default=1.0)
    PARSER.add_argument('-estick',help='sticking probability',                 type=float, default=1.0)
    PARSER.add_argument('-xeuv',  help='XEUV mass loss rate [Msun/year]',      type=float, default=0.0)
    PARSER.add_argument('-dir',   help='output directory default: data/',      type=str,   default='data')

    PARSER.add_argument('-p',               help='produce plots if possible',  action='store_true')
    PARSER.add_argument('-g','--gasevol',   help='turn *off* gas evolution',   action='store_false')
    ARGSIN = PARSER.parse_args()

    # convert units to cgs

    ARGSIN.tmax  *= c.year
    ARGSIN.mstar *= c.M_sun
    ARGSIN.rstar *= c.R_sun
    ARGSIN.rc    *= c.AU
    ARGSIN.rt    *= c.AU
    ARGSIN.mdisk *= ARGSIN.mstar

    # convert to arguments object

    ARGS = args()
    for name,_ in ARGS.varlist:
        if hasattr(ARGSIN,name):
            setattr(ARGS,name,getattr(ARGSIN, name))

    # call the wrapper

    wrapper.model_wrapper(ARGS,save=True,plot=ARGSIN.p)

if __name__=='__main__':
    main()
